### ISSUE TITLE
Grammatical errors and other such bullshit nobody particularly cares about.

### ISSUE THREAD

**Issue by Montenico** [Gravydigger/Gravydigger.github.io#15]
Hi, yes, hello. I have noticed some small typos and, as the one person who cares, it is my duty to SCOUR THIS WRETCHED PROJECT OF ALL GRAMMATICAL MISTAKES TO AVOID THE DECAY OF THE ENGLISH LANGUAGE! 
Or it would be, if the English language didn't already suck...
Some of these are really nitpicky, and some aren't even really grammatically incorrect but just slightly change the flow of a sentence. Yes, I am very bored. Yes, I am a little sorry for this. It would be really funny if someone found a typo in this.
Anyway...

- Home page:
1. "but also for the worlds knowledge" should be "but also for the world's knowledge".

- About page:
1. "learn how to use a servers" should be either "learn how to use a server" or "learn how to use servers" (depending on whether it's supposed to be singular or plural).

- Installing Arch Linux, a Guided Walkthrough post:
1. In the first paragraph of the _Connecting the Internet_ section (should it be "Connecting _to_ the internet"? Maybe.) both instances of the word "your" should be changed to "you're".
2. In the first paragraph of the _Partitioning the disk_ section, in order to be a shortened version of "because" the word "cause" should have an apostrophe at the start ('cause). (Yes. I am going to be THAT nitpicky.)
3. In the _LVM With Encryption_ section, the usage of "Regardless if" is not gramatically correct. "Regardless of if" (which sounds bad, if you ask me) or "Regardless of whether" would be grammatically correct.
4. I believe the sentence "Now we’ve set up everything, now we can actually start to install Arch Linux onto your system, how exciting!" would be slightly better as "Now that we’ve set up everything, we can actually start to install Arch Linux onto your system. How exciting!"
5. The sentence "We’ll need to install the base package, as well as Linux itself of course!" could use a comma before the "of course".
6. The sentence "Now as for packages [...]" could use a comma between "Now" and "as".
7. There should NOT be a comma in "[...] just in case something breaks in the kernel, and you need to head to a known LTS version".
8. The sentence "If you want Wi-Fi support you’ll need these." should have a comma after "support".
9. The sentence "Recommended even if you’re not going to use Wi-Fi in case you need them down the road." could use a comma after Wi-Fi.
10. _Network config_ section. There's a "your" in the second paragraph that should be a "you're". (Took a while to find another typo. Despite what this may make it look like, you did a good job!)
11. In the second paragraph of the _The Bootloader_ section, it says "Copy the follow text into", when it should be "Copy the **following** text into".
12. In the sentence "First, we want to set a label for our encrypted partition, let’s call it...", change that second comma for a period. (And remember to capitalize the L afterwards!)
13. In the _Desktop Environment_ section, it says "If you have use Nvidia". Drop either the "have" or the "use".
14. In the _Generating a Swapfile_ section. Add an "of" between "some" and "the" in "A swapfile is where the operating system can place some the unused RAM contents".
15. In the _Enable Setup Mode_ section, it says "You’ll first need the enter the UEFI". I'm assuming that's supposed to say "You’ll first need **to** enter the UEFI"
16. In the same paragraph as the previous point it says "[...] it will most likely be under “Security” banner." I believe there should be a "the" after "under".
17. In the very last paragraph of the blog post, "desktop environment’s" has an apostrophe that shouldn't be there.

- How and Why I Made This Blog post:
1. First paragraph. In "Now at this point [...]" should have a comma after "now". Put a comma after using "Now" as a discourse marker. Don't do it when using it as an adverb. I'll stop pointing it out now, but it does happen later.
2. Second paragraph. In "Now I’d probably should have", should be "Now, I probably should have"
3. Third paragraph. It says "there were a few issues with it that was caused due to my inexperience." That "was" should be a "were".
4. Third paragraph. It says "While this isn’t a bit deal". Pretty sure you mean "big deal". (Unlike all the corrections I'm making, which are no big deal despite the fact this has over 4000 characters).
5. "keep a public record for what they have done". "a public record **of** what they have done" would probably be better? I don't know anymore. It's 5 AM.
6. In "I like the idea of publicly accessible archive of my thoughts" you should put an "a" before "publicly".
7. "Now with the preamble out of the way let’s get to the meat of this post." Nothing wrong with this sentence, but a comma after "now" and "way" would make it flow slightly better.
8. When you say "piggyback on someone else’s work that knows what they are doing", it should be "piggyback on the work of someone else who knows what they are doing"
9. There should be a comma before "as" in "I decided to go with Astro Cactus as it had a very minimalistic appearance", apparently.
10. "With the templated installed in my own GitHub repo" shouldn't have that "d" in "template".
11. Not a mistake. Just a short break to mention I love Grefi.
12. In "(note that the d attribute has been omitted for clarify)", change "clarify" with "clarity".
13. Modify the sentence "With those modification, we get this:" by adding an s so it reads "modifications".
14. The sentence "which lead me looking at KaTeX." would be better with a "to" after "lead".

And that's about it. As I said, I think some of those technically aren't even grammatically incorrect. I am just being annoying. This (probably) won't happen again. (Or at least I won't be suggesting that many tiny changes in punctuation).
This is as good a time as any to remind you that you are great and to wish you an excellent day.
I'm going to sleep now.

**Comment by Gravydigger** [comment]
I...
Alrighty then.

**Comment by Gravydigger** [comment]
Changes have now been fixed in commit a64cbaea.
Note that I decided to ommit placing a coma after "Now" in some of these sentences as I personally find it reads better in my head, so they have not been changed.
Thank you for pointing these out.
